
DROP DATABASE IF EXISTS TWITTER;
CREATE DATABASE IF NOT EXISTS TWITTER;
USE TWITTER;

CREATE TABLE `TwitterAxiata` (
    `tweet_id` VARCHAR(20) NOT NULL,
	`screen_name` VARCHAR(60),
	`created_at` DATETIME,
	`text` VARCHAR(3000)
);